import "./globals.css";
import type { Metadata } from "next";

import localFont from "next/font/local";

const font = localFont({
  src: "../font/WantedSansVariable.woff2",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={font.className} data-theme="dark">
      <body>{children}</body>
    </html>
  );
}
